#themes
[general]
import = [
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml",
  # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

[terminal]
shell = "/bin/zsh"

[window.padding]
x = 15
y = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

[env]
term = "xterm-256color"
